flag_value {
  package: "com.android.systemui"
  name: "notification_throttle_hun"
  state: ENABLED
  permission: READ_ONLY
}

flag_value {
  package: "com.android.systemui"
  name: "fast_unlock_transition"
  state: ENABLED
  permission: READ_ONLY
}

flag_value {
  package: "com.android.systemui"
  name: "qs_ui_refactor_compose_fragment"
  state: ENABLED
  permission: READ_ONLY
}

flag_value {
  package: "com.android.systemui"
  name: "qs_ui_refactor"
  state: ENABLED
  permission: READ_ONLY
}

flag_value {
  package: "com.android.systemui"
  name: "notification_shade_blur"
  state: ENABLED
  permission: READ_ONLY
}

flag_value {
  package: "com.android.systemui"
  name: "notification_background_tint_optimization"
  state: ENABLED
  permission: READ_ONLY
}

flag_value {
  package: "com.android.systemui"
  name: "notifications_redesign_footer_view"
  state: ENABLED
  permission: READ_ONLY
}

flag_value {
  package: "com.android.systemui"
  name: "notifications_redesign_guts"
  state: ENABLED
  permission: READ_ONLY
}

flag_value {
  package: "com.android.systemui"
  name: "disable_blurred_shade_visible"
  state: ENABLED
  permission: READ_ONLY
}

flag_value {
  package: "com.android.systemui"
  name: "magnetic_notification_swipes"
  state: ENABLED
  permission: READ_ONLY
}

flag_value {
  package: "com.android.systemui"
  name: "notification_footer_background_tint_optimization"
  state: ENABLED
  permission: READ_ONLY
}

flag_value {
  package: "com.android.systemui"
  name: "physical_notification_movement"
  state: ENABLED
  permission: READ_ONLY
}

flag_value {
  package: "com.android.systemui"
  name: "status_bar_popup_chips"
  state: ENABLED
  permission: READ_ONLY
}

flag_value {
  package: "com.android.systemui"
  name: "status_bar_chips_return_animations"
  state: ENABLED
  permission: READ_ONLY
}
