# Set all versions
CHERISH_BUILD_TYPE ?= UNOFFICIAL

CUSTOM_DATE_YEAR := $(shell date -u +%Y)
CUSTOM_DATE_MONTH := $(shell date -u +%m)
CUSTOM_DATE_DAY := $(shell date -u +%d)
CUSTOM_DATE_HOUR := $(shell date -u +%H)
CUSTOM_DATE_MINUTE := $(shell date -u +%M)
CUSTOM_BUILD_DATE_UTC := $(shell date -d '$(CUSTOM_DATE_YEAR)-$(CUSTOM_DATE_MONTH)-$(CUSTOM_DATE_DAY) $(CUSTOM_DATE_HOUR):$(CUSTOM_DATE_MINUTE) UTC' +%s)
CUSTOM_BUILD_DATE := $(CUSTOM_DATE_YEAR)$(CUSTOM_DATE_MONTH)$(CUSTOM_DATE_DAY)-$(CUSTOM_DATE_HOUR)$(CUSTOM_DATE_MINUTE)

CUSTOM_PLATFORM_VERSION := 10.0

CHERISH_VERSION := v1.1

CUSTOM_DATE_CODE := $(CUSTOM_DATE_HOUR)$(CUSTOM_DATE_MINUTE)

TARGET_PRODUCT_SHORT := $(subst cherish_,,$(CUSTOM_BUILD))

CUSTOM_VERSION := Cherish-OS-$(CHERISH_VERSION)-$(CUSTOM_BUILD_DATE)-$(CUSTOM_BUILD)-$(CHERISH_BUILD_TYPE)
CUSTOM_VERSION_PROP := ten

CUSTOM_PROPERTIES := \
    ro.cherish.version=$(CUSTOM_VERSION_PROP) \
    ro.cherish.version.display=$(CUSTOM_VERSION) \
    ro.cherish.build_date=$(CUSTOM_BUILD_DATE) \
    ro.cherish.build_date_utc=$(CUSTOM_BUILD_DATE_UTC) \
    ro.cherish.build_type=$(CHERISH_BUILD_TYPE) \
    ro.cherish.version=$(CHERISH_VERSION)